name=TM1637Display
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Library for TM1637 2..6 Digit 7-Segment LED Display
paragraph=**PRELIMINARY**
category=Display
includes=TM1637Display.h
url=https://github.com/mumanchu/TM1637Display
architectures=*

